### ISSUE TITLE
React must be in scope when using JSX react/react-in-jsx-scope

### ISSUE THREAD

**Issue by sanketshivale** [neerajadhav/ReactFakeShop#1]
There might be an error in App.js as you have not imported React

![react](https://user-images.githubusercontent.com/85338561/179038596-d4551a1b-1e21-4bf4-b08b-3a1b4def2d2a.jpeg)

**Comment by neerajadhav** [comment]
Starting from React 17 it's not necessary to import React to use JSX.
Because the new JSX transform will automatically import the necessary react/jsx-runtime functions, React will no longer need to be in scope when you use JSX.

Try to update your React version
